# logo
favicon:
  visibilitychange: true

top_bars:
  - title: menu.home
    url: /
  - title: menu.archives
    url: /archives/
  - title: menu.links
    url: /links/
  - title: menu.about
    url: /about/
  - title: 自定义
    url: /customize_page/

banner:
  index:
    bgurl: [/img/bg.jpg,/img/banner.png]

sidebar:
  typedTextPrefix: I`m
  typedText: [ 'Web Developer' ]
  info: 
    - key: 文档地址
      val: <a href="https://hexo-theme-async.imalun.com/" target="_blank" rel="nofollow">查看</a>  
    - key: 备用地址
      val: <a href="https://async-docs.imalun.com/" target="_blank" rel="nofollow">查看</a>   
    - key: 提交示例站点
      val: <a href="https://hexo-theme-async.imalun.com/demo/" target="_blank" rel="nofollow">查看</a>   

  social:
    - icon: fab fa-github
      url: https://github.com/MaLuns/Hexo-theme-async
      name: Github
    - icon: fab fa-npm
      url: https://www.npmjs.com/package/hexo-theme-async
      name: Npm

footer:
  powered:
    enable: true
  beian:
    enable: false
    icp: 
  copyrightYear: 2022
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 2022/04/10 17:00:00
  custom_text:

search:
  enable: true
  type: local
  preload: true
  trigger: auto

baidu_push: true

reward:
  enable: true
  methods:
    - name: 微信
      path: https://mp-8b005489-7724-4f8c-afdd-30192ff4f7ae.cdn.bspapp.com/cloudstorage/61a57135-2e65-4d51-8be1-03b8bd1c595e.jpg
    - name: 支付宝
      path: https://mp-8b005489-7724-4f8c-afdd-30192ff4f7ae.cdn.bspapp.com/cloudstorage/a21e9954-22f2-43fe-b3b0-3dba1fdde3ed.jpg
    - name: QQ
      path: https://mp-8b005489-7724-4f8c-afdd-30192ff4f7ae.cdn.bspapp.com/cloudstorage/69fb1903-d0dc-4169-9a02-1e76ec8e7761.jpg

creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true

swup: true

toc:
  enable: true
  list_number: true
  max_depth: 3
  min_depth: 1

rightside:
  readmode: true
  aside: true

post_pagination: 
  enable: true 
  type: small

cdn:
  js:
    head:
    base: [demo.js]

assets:
    third_party_provider: https://npm.elemecdn.com

highlight:
  title: mac
  height_limit: 200